### ISSUE TITLE
No apparent way to establish XamlStyler settings

### ISSUE THREAD

**Issue by IndianaGary** [zmrbak/XamlStyler#1]
The original XamlStyler provides an editor to allow the user a way to set the styler's options. 

I realize that this might be beyond the scope of the current implementation, but providing a way to inject options (for example, by placing a XamlStyler.json file in the project root or somewhere up the directory tree ending at the root of the drive) would ameliorate the problem. One could then use the VS2019 version of the styler to set the options and the VS2022 version could read them, ignoring anything it did not support.

**Comment by zmrbak** [comment]
Now the original XamlStyler is supported by VS2022.
The code is [here](https://dev.azure.com/xavalon/XAML%20Styler/_build/results?buildId=401&view=artifacts&type=publishedArtifacts)

**Comment by IndianaGary** [comment]
Thanks you, I’ll check it out!

 

Regards, 

Gary
